header:
  license:
    spdx-id: MIT
    copyright-owner: Corinvo, LLC.
    content: |
      Copyright (c) {year} Corinvo, LLC. and affiliates.
      Licensed under the MIT License

  paths:
    - '**/*.ts'
    - '**/*.tsx'
    - '**/*.js'
    - '**/*.jsx'
    - '**/*.scss'
    - '**/*.css'
    - '**/*.hbs'

  paths-ignore:
    - 'dist/**'
    - 'node_modules/**'
    - '**/*.d.ts'
    - '**/template-registry.ts'

  language:
    TypeScript:
      extensions:
        - '.ts'
        - '.tsx'
      comment_style_id: SlashAsterisk

    JavaScript:
      extensions:
        - '.js'
        - '.jsx'
      comment_style_id: SlashAsterisk

    CSS:
      extensions:
        - '.css'
        - '.scss'
      comment_style_id: SlashSlash

    Handlebars:
      extensions:
        - '.hbs'
      comment_style_id: HTMLComment
