header:
  license:
    spdx-id: MIT
    copyright-owner: Corinvo, LLC.
    content: |
      Copyright (c) {year} Corinvo, LLC. and affiliates.
      Licensed under the MIT License

  commentStyle:
    start: "/*"
    end: "*/"
    line: "//"

  paths:
    - '**/*.ts'
    - '**/*.tsx'
    - '**/*.js'
    - '**/*.jsx'
    - '**/*.scss'
    - '**/*.css'
    - '**/*.hbs'

  paths-ignore:
    - 'dist/**'
    - 'node_modules/**'
    - '**/*.d.ts'
    - '**/template-registry.ts'